language: php

php:
  - 8.2
  - 8.3
  - 8.4

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - composer test -- --coverage-clover=coverage.xml

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

notifications:
    on_success: never
    on_failure: always